-- ================================================================
-- Unique product images - every product has its own unique image
-- Images self-hosted in Supabase Storage (product-images bucket)
-- Generated: 2026-02-27T16:17:45.283Z
-- ================================================================

UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/amber-silver-ring.jpg"]' WHERE title = 'Amber & Silver Ring';
UPDATE products SET images = '["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&fit=crop&q=80"]' WHERE title = 'Amber Chess Set - Mini';
UPDATE products SET images = '["https://images.unsplash.com/photo-1590548784585-643d2b9f2925?w=800&fit=crop&q=80"]' WHERE title = 'Amber Cufflinks';
UPDATE products SET images = '["https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&fit=crop&q=80"]' WHERE title = 'Amber Earrings - Honey Color';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/amber-gift-box-set.jpg"]' WHERE title = 'Amber Gift Box Set';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/amber-keychain.jpg"]' WHERE title = 'Amber Keychain';
UPDATE products SET images = '["https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&fit=crop&q=80"]' WHERE title = 'Amber Ring - Cognac Color';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/amber-rosary-beads.jpg"]' WHERE title = 'Amber Rosary Beads';
UPDATE products SET images = '["https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=800&fit=crop&q=80"]' WHERE title = 'Baltic Amber Pendant Necklace';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/beeswax-wrap-set.jpg"]' WHERE title = 'Beeswax Wrap Set';
UPDATE products SET images = '["https://images.unsplash.com/photo-1597225244660-1cd128c64284?w=800&fit=crop&q=80"]' WHERE title = 'Birch Bark Container';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/black-ceramic-bowl-set.jpg"]' WHERE title = 'Black Ceramic Bowl Set';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/carved-walking-stick.jpg"]' WHERE title = 'Carved Walking Stick';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/carved-wooden-box.jpg"]' WHERE title = 'Carved Wooden Box';
UPDATE products SET images = '["https://images.unsplash.com/photo-1603204077779-bed963ea7d0e?w=800&fit=crop&q=80"]' WHERE title = 'Ceramic Candle Holder Set';
UPDATE products SET images = '["https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800&fit=crop&q=80"]' WHERE title = 'Ceramic Coffee Mug Set';
UPDATE products SET images = '["https://images.unsplash.com/photo-1590422749897-47036da0b0ff?w=800&fit=crop&q=80"]' WHERE title = 'Ceramic Dinner Plate Set';
UPDATE products SET images = '["https://images.unsplash.com/photo-1622428051717-dcd8412959de?w=800&fit=crop&q=80"]' WHERE title = 'Ceramic Garden Planter';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/ceramic-honey-jar.jpg"]' WHERE title = 'Ceramic Honey Jar';
UPDATE products SET images = '["https://images.unsplash.com/photo-1493106641515-6b5631de4bb9?w=800&fit=crop&q=80"]' WHERE title = 'Ceramic Oil Lamp';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/ceramic-salt-pepper-set.jpg"]' WHERE title = 'Ceramic Salt & Pepper Set';
UPDATE products SET images = '["https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&fit=crop&q=80"]' WHERE title = 'Ceramic Soup Bowl Set';
UPDATE products SET images = '["https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&fit=crop&q=80"]' WHERE title = 'Ceramic Tea Set';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/clay-butter-dish.jpg"]' WHERE title = 'Clay Butter Dish';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/clay-jug-traditional.jpg"]' WHERE title = 'Clay Jug - Traditional';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/craft-workshop-gift-card.jpg"]' WHERE title = 'Craft Workshop Gift Card';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/cross-stitch-sampler-kit.jpg"]' WHERE title = 'Cross-Stitch Sampler Kit';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/decorated-easter-egg-collection.jpg"]' WHERE title = 'Decorated Easter Egg Collection';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/decorative-black-clay-plate.jpg"]' WHERE title = 'Decorative Black Clay Plate';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/decorative-wall-plate.jpg"]' WHERE title = 'Decorative Wall Plate';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/decorative-willow-bowl.jpg"]' WHERE title = 'Decorative Willow Bowl';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/decorative-wooden-bowl.jpg"]' WHERE title = 'Decorative Wooden Bowl';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/decorative-wreath.jpg"]' WHERE title = 'Decorative Wreath';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/diy-craft-kit-ceramics.jpg"]' WHERE title = 'DIY Craft Kit - Ceramics';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/diy-craft-kit-weaving.jpg"]' WHERE title = 'DIY Craft Kit - Weaving';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/dried-flower-bouquet.jpg"]' WHERE title = 'Dried Flower Bouquet';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/embroidered-guest-towels.jpg"]' WHERE title = 'Embroidered Guest Towels';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/embroidered-pillow-cover.jpg"]' WHERE title = 'Embroidered Pillow Cover';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/essential-oil-diffuser.jpg"]' WHERE title = 'Essential Oil Diffuser';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/felted-wool-brooch.jpg"]' WHERE title = 'Felted Wool Brooch';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/felted-wool-scarf.jpg"]' WHERE title = 'Felted Wool Scarf';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/felted-wool-slippers.jpg"]' WHERE title = 'Felted Wool Slippers';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/forged-door-handle.jpg"]' WHERE title = 'Forged Door Handle';
UPDATE products SET images = '["https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=800&fit=crop&q=80"]' WHERE title = 'Forged Iron Candelabra';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/glazed-flower-pot.jpg"]' WHERE title = 'Glazed Flower Pot';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/green-amber-pendant.jpg"]' WHERE title = 'Green Amber Pendant';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/hand-bound-notebook.jpg"]' WHERE title = 'Hand-Bound Notebook';
UPDATE products SET images = '["https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=800&fit=crop&q=80"]' WHERE title = 'Hand-Painted Ceramic Tile';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/hand-painted-ornament-set.jpg"]' WHERE title = 'Hand-Painted Ornament Set';
UPDATE products SET images = '["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&fit=crop&q=80"]' WHERE title = 'Hand-Printed Linen Tote';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/handcarved-cutting-board.jpg"]' WHERE title = 'Handcarved Cutting Board';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/handcrafted-wooden-cutting-board.jpg"]' WHERE title = 'Handcrafted Wooden Cutting Board';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/handmade-greeting-cards-5.jpg"]' WHERE title = 'Handmade Greeting Cards (5)';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/handmade-incense-holder.jpg"]' WHERE title = 'Handmade Incense Holder';
UPDATE products SET images = '["https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&fit=crop&q=80"]' WHERE title = 'Handwoven Linen Scarf';
UPDATE products SET images = '["https://images.unsplash.com/photo-1600369672770-985fd30004eb?w=800&fit=crop&q=80"]' WHERE title = 'Handwoven Wool Blanket';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/herb-drying-rack.jpg"]' WHERE title = 'Herb Drying Rack';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/herbal-tea-blend-set.jpg"]' WHERE title = 'Herbal Tea Blend Set';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/iron-garden-hook.jpg"]' WHERE title = 'Iron Garden Hook';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/large-laundry-basket.jpg"]' WHERE title = 'Large Laundry Basket';
UPDATE products SET images = '["https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=800&fit=crop&q=80"]' WHERE title = 'Lavender Sachet Set';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/linen-apron.jpg"]' WHERE title = 'Linen Apron';
UPDATE products SET images = '["https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=800&fit=crop&q=80"]' WHERE title = 'Linen Bread Bag';
UPDATE products SET images = '["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&fit=crop&q=80"]' WHERE title = 'Linen Curtain Pair';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/linen-kitchen-towels-set.jpg"]' WHERE title = 'Linen Kitchen Towels Set';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/linen-napkin-set-6.jpg"]' WHERE title = 'Linen Napkin Set (6)';
UPDATE products SET images = '["https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&fit=crop&q=80"]' WHERE title = 'Linen Table Cloth';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/lithuanian-sun-pendant.jpg"]' WHERE title = 'Lithuanian Sun Pendant';
UPDATE products SET images = '["https://images.unsplash.com/photo-1622372738946-62e02505feb3?w=800&fit=crop&q=80"]' WHERE title = 'Macrame Plant Hanger';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/mini-gift-baskets-set-3.jpg"]' WHERE title = 'Mini Gift Baskets Set (3)';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/miniature-ceramic-village.jpg"]' WHERE title = 'Miniature Ceramic Village';
UPDATE products SET images = '["https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&fit=crop&q=80"]' WHERE title = 'Modern Ceramic Planter';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/natural-lip-balm-set.jpg"]' WHERE title = 'Natural Lip Balm Set';
UPDATE products SET images = '["https://images.unsplash.com/photo-1607006344380-b6775a0824a7?w=800&fit=crop&q=80"]' WHERE title = 'Natural Soap Set';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/oak-cheese-board.jpg"]' WHERE title = 'Oak Cheese Board';
UPDATE products SET images = '["https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&fit=crop&q=80"]' WHERE title = 'Oak Picture Frame';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/patchwork-quilt-small.jpg"]' WHERE title = 'Patchwork Quilt - Small';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/premium-amber-necklace.jpg"]' WHERE title = 'Premium Amber Necklace';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/pressed-flower-frame.jpg"]' WHERE title = 'Pressed Flower Frame';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/raku-fired-vase.jpg"]' WHERE title = 'Raku Fired Vase';
UPDATE products SET images = '["https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=800&fit=crop&q=80"]' WHERE title = 'Raw Amber Bracelet';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/silver-oak-leaf-brooch.jpg"]' WHERE title = 'Silver Oak Leaf Brooch';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/straw-christmas-ornament-set.jpg"]' WHERE title = 'Straw Christmas Ornament Set';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/straw-crown-decoration.jpg"]' WHERE title = 'Straw Crown Decoration';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/straw-star-ornament-set.jpg"]' WHERE title = 'Straw Star Ornament Set';
UPDATE products SET images = '["https://images.unsplash.com/photo-1560421683-6856ea585c78?w=800&fit=crop&q=80"]' WHERE title = 'Toy Wooden Train';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/traditional-black-ceramic-vase.jpg"]' WHERE title = 'Traditional Black Ceramic Vase';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/traditional-candle-set.jpg"]' WHERE title = 'Traditional Candle Set';
UPDATE products SET images = '["https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=800&fit=crop&q=80"]' WHERE title = 'Traditional Clay Pot - Large';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/traditional-decorated-easter-egg.jpg"]' WHERE title = 'Traditional Decorated Easter Egg';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/traditional-linen-shawl.jpg"]' WHERE title = 'Traditional Linen Shawl';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/traditional-linen-table-runner.jpg"]' WHERE title = 'Traditional Linen Table Runner';
UPDATE products SET images = '["https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=800&fit=crop&q=80"]' WHERE title = 'Traditional Paper Cut Art';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/traditional-sash-belt.jpg"]' WHERE title = 'Traditional Sash Belt';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/traditional-spinning-top.jpg"]' WHERE title = 'Traditional Spinning Top';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/traditional-straw-mobile-large.jpg"]' WHERE title = 'Traditional Straw Mobile - Large';
UPDATE products SET images = '["https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&fit=crop&q=80"]' WHERE title = 'Traditional Straw Mobile - Small';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/wheel-thrown-clay-pitcher.jpg"]' WHERE title = 'Wheel-Thrown Clay Pitcher';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/wicker-bread-basket.jpg"]' WHERE title = 'Wicker Bread Basket';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/wicker-storage-basket-medium.jpg"]' WHERE title = 'Wicker Storage Basket - Medium';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/wicker-wall-shelf.jpg"]' WHERE title = 'Wicker Wall Shelf';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/willow-picnic-basket.jpg"]' WHERE title = 'Willow Picnic Basket';
UPDATE products SET images = '["https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=800&fit=crop&q=80"]' WHERE title = 'Willow Shopping Basket';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/wooden-book-ends.jpg"]' WHERE title = 'Wooden Book Ends';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/wooden-candle-holders-pair.jpg"]' WHERE title = 'Wooden Candle Holders (Pair)';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/wooden-chess-set.jpg"]' WHERE title = 'Wooden Chess Set';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/wooden-coat-rack.jpg"]' WHERE title = 'Wooden Coat Rack';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/wooden-herb-planter.jpg"]' WHERE title = 'Wooden Herb Planter';
UPDATE products SET images = '["https://images.unsplash.com/photo-1588412079929-790b9f593d8e?w=800&fit=crop&q=80"]' WHERE title = 'Wooden Jewelry Box';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/wooden-kitchen-utensil-set.jpg"]' WHERE title = 'Wooden Kitchen Utensil Set';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/wooden-salad-servers.jpg"]' WHERE title = 'Wooden Salad Servers';
UPDATE products SET images = '["https://images.unsplash.com/photo-1605629921711-2f6b00c6bbf4?w=800&fit=crop&q=80"]' WHERE title = 'Wooden Serving Platter';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/wooden-spoon-collection.jpg"]' WHERE title = 'Wooden Spoon Collection';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/wooden-toy-blocks-set.jpg"]' WHERE title = 'Wooden Toy Blocks Set';
UPDATE products SET images = '["https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=800&fit=crop&q=80"]' WHERE title = 'Wooden Wall Clock';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/wooden-whistle.jpg"]' WHERE title = 'Wooden Whistle';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/wooden-wine-rack.jpg"]' WHERE title = 'Wooden Wine Rack';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/woven-bed-runner.jpg"]' WHERE title = 'Woven Bed Runner';
UPDATE products SET images = '["https://images.unsplash.com/photo-1594040226829-7f251ab46d80?w=800&fit=crop&q=80"]' WHERE title = 'Woven Belt - Traditional';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/woven-coaster-set-4.jpg"]' WHERE title = 'Woven Coaster Set (4)';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/woven-dream-catcher.jpg"]' WHERE title = 'Woven Dream Catcher';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/woven-placemat-set-4.jpg"]' WHERE title = 'Woven Placemat Set (4)';
UPDATE products SET images = '["https://images.unsplash.com/photo-1596455607563-ad6193f76b17?w=800&fit=crop&q=80"]' WHERE title = 'Woven Wall Tapestry';
UPDATE products SET images = '["https://adtzxfiurwefcjhzdrjx.supabase.co/storage/v1/object/public/product-images/woven-wire-earrings.jpg"]' WHERE title = 'Woven Wire Earrings';

-- Verify: should return 124 rows, all with unique image URLs
-- SELECT title, images->0 as image_url FROM products WHERE status = 'active' ORDER BY title;

